# 注册页面
USER_EXIST = 1
REG_SUCCESS = 2

# 登陆页面
USER_NOTEXIST = 1
PWD_INCORRECT = 2
LOGIN_SUCCESS = 3
LOGIN_ADMIN_SUCCESS = 4

# 设置页面
OLD_PWD_ERROR = 1
SET_SUCCESS = 2
__C = dict()
VOCAB_CET4 = 1
VOCAB_CET6 = 2
VOCAB_TOEFL = 4
VOCAB_GRE = 8
__C['cet-4'] = VOCAB_CET4
__C['cet-6'] = VOCAB_CET6
__C['toefl'] = VOCAB_TOEFL
__C['gre'] = VOCAB_GRE
NEW_USER = 10
OLD_USER = 11
NEW_USER_PLAN = 20
NEW_USER_VOACB = VOCAB_CET4


#背诵准备(memorize-in)
NOT_SELECT_VOCAB = 1
MEM_IN_SUCCESS = 2
MEM_FINISH_VOCAB = 3
MEM_OUT_SUCCESS = 4

#单词测验
TEST_CHOICE = 5   #测验选择题数量
TEST_SPELLING = 5 #测验拼写题数量
TEST_SUCCESS = 200

#管理员更改
NOT_INPUT_USER = 1
MODIFY_SUCCESS = 2
NO_SUCH_USER = 3
DELETE_SUCCESS = 4

# Cookie/连接
COOKIE_EXPIRE = 60 * 30 # 10 minutes
USER_EXPIRE = 203